### ISSUE TITLE
Does not work with 1.10.x

### ISSUE THREAD

**Issue by sindastra** [TerrorBite/MinecraftBot#7]
MinecraftBot does not seem to work with 1.10.x at all.

As soon as it tries to connect, a few exceptions occur, and that's it.

What I know so far:

1. scheduleAsyncRepeatingTask() is deprecated

2. This output:

[14:41:33 INFO]: [MinecraftBot] Connecting to <removed for privacy>... (Attempt 1)
[14:41:33 WARN]: Exception in thread "Craft Scheduler Thread - 2"
[14:41:33 WARN]: Exception in thread "Craft Scheduler Thread - 1"
[14:41:33 WARN]: org.apache.commons.lang.UnhandledException: Plugin MinecraftBot v2.3.0 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.avisenera.minecraftbot.Metrics.postPlugin(Metrics.java:334)
        at com.avisenera.minecraftbot.Metrics.access$400(Metrics.java:68)
        at com.avisenera.minecraftbot.Metrics$1.run(Metrics.java:243)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[14:41:33 WARN]: org.apache.commons.lang.UnhandledException: Plugin MinecraftBot v2.3.0 generated an exception while executing task 6
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.avisenera.minecraftbot.MinecraftBot.log(MinecraftBot.java:71)
        at com.avisenera.minecraftbot.listeners.IRCManager.start(IRCManager.java:115)
        at com.avisenera.minecraftbot.listeners.IRCManager.start(IRCManager.java:86)
        at com.avisenera.minecraftbot.listeners.IRCManager.run(IRCManager.java:75)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Artox** [comment]
It looks like this is the real cause, no need to worry about depercation!:
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at com.avisenera.minecraftbot.Metrics.postPlugin(Metrics.java:334)

**Comment by shane-smith** [comment]
I haven't used MinecraftBot in a while. @TerrorBite ?

**Comment by sindastra** [comment]
Well, I tested it on a new and clean server (and build), no other plugins were installed to make sure nothing is interfering, and it did not work. You can see the output up there as I posted it.

**Comment by shane-smith** [comment]
Try setting 'send_log_to_ops' to false in the config.yml and see if that resolves the problem.

**Comment by sindastra** [comment]
That seems to work as temporary workaround. It is now able to connect, join and message back and forth. It still throws an exception though:

[21:49:04 INFO]: [MinecraftBot] Connecting to <removed for privacy>... (Attempt 1)
[21:49:04 WARN]: Exception in thread "Craft Scheduler Thread - 131"
[21:49:04 WARN]: org.apache.commons.lang.UnhandledException: Plugin MinecraftBot v2.3.0 generated an exception while executing task 13
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.avisenera.minecraftbot.Metrics.postPlugin(Metrics.java:334)
        at com.avisenera.minecraftbot.Metrics.access$400(Metrics.java:68)
        at com.avisenera.minecraftbot.Metrics$1.run(Metrics.java:243)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by shane-smith** [comment]
Okay, thanks. I'll commit that as a workaround so that the plugin works with the default settings.

I'll leave this defect open though until a more suitable fix is applied.

**Comment by TerrorBite** [comment]
> java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()

It looks like this is a result of deprecation. The version that returns an array of Players has been removed, the replacement returns a Collection<? extends Player>. This should be a relatively easy fix.

**Comment by shane-smith** [comment]
Reverted the temporary config change that I made. PR #8 fixed the issue.
